services:
  db:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge