services:
  db:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - todo-net
    volumes:
      - postgres-data:/var/lib/postgresql/data

  todo-app:
    build: .
    container_name: todo-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tododb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8084
    ports:
      - "8084:8084"
    networks:
      - todo-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  todo-net:
    driver: bridge

volumes:
  postgres-data: