apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    server.port=8085
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    management.endpoints.web.exposure.include=health,info
    management.endpoint.health.show-details=always