name: Deploy Latest DockerHub Image to Local K8s

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ike20743/todo-app:latest

jobs:
  deploy-to-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kind and kubectl
        run: |
          # Install kind (Kubernetes in Docker)
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

          # Install kubectl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Create a local Kubernetes cluster
        run: kind create cluster --wait 5m

      - name: Test cluster connection
        run: kubectl cluster-info

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/

      - name: Force deployment to pull latest image
        run: kubectl rollout restart deployment/todo-app