name: Build → Docker Hub → Deploy to LocalStack
on:
  push:
    branches: [ master ]

env:
  DOCKERHUB_IMAGE: ike2043/todo-app  # Change this!
  ECS_CLUSTER: todo-cluster
  ECS_SERVICE: todo-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # --- STAGE 1: Checkout & Build ---
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      # --- STAGE 2: Docker Hub Push ---
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Docker Hub
        run: |
          docker build -t ${{ env.DOCKERHUB_IMAGE }}:latest .
          docker push ${{ env.DOCKERHUB_IMAGE }}:latest

      # --- STAGE 3: LocalStack Deploy ---
      - name: Configure LocalStack AWS
        run: |
          aws configure set aws_access_key_id test
          aws configure set aws_secret_access_key test
          aws configure set region us-east-1
          aws configure set default.endpoint_url http://localhost:4566

      - name: Trigger ECS Deployment
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --force-new-deployment \
            --endpoint-url http://localhost:4566