name: Terraform Plan/Apply

on:
  push:
    branches: [ "master" ]

env:
  AWS_DEFAULT_REGION: us-east-1
  LOCALSTACK_ENDPOINT: http://localhost:4566

jobs:
  terraform:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack-pro
        ports:
          - "4566:4566"
        env:
          SERVICES: s3,ec2,eks,iam,ecr,ecs
          LOCALSTACK_APIKEY: ${{ secrets.LOCALSTACK_APIKEY }}
          DEBUG: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform